yes:
        0:
            area: 
                - "yes"
            landuse: "*"
            area:highway: "*"
            building: "*"
            leisure: "*"
            aeroway: "*"
            natural: "*"
            waterway: 
                - riverbank
            amenity:
                - parking
                - fuel
no:
        1:
            area: 
                - "no"
	    natural:
	    	- "tree_row"
