yes:
        0:
            bridge: "*"
            man_made:
                - bridge
            layer:
                - "1"
                - "2"
                - "3"
                - "4"
                - "5"

no:
        0:
            bridge:
                - "no"
