IGNORE:
        1:
            barrier: bollard	
            foot: yes
BARRIER: 
        0:
            barrier : "*"

STOP:
        0:
                public_transport:
                        - stop_position
TRAFFIC_LIGHTS:
        0:        
                crossing:
                        - traffic_signals
