speeds:
        WAY: 4
        PARK: 3
        GREEN: 3
        FOREST: 2
        PAVED: 4
        UNPAVED: 3
        STEPS: 2
        HIGHWAY: 4
        DIRECT: 3

ratios:
        PARK: 1
        GREEN: 1
        FOREST: 0.75
        PAVED: 1.2
        UNPAVED: 1
        STEPS: 0.6
        HIGHWAY: 1.2
        DIRECT: 0.8
heights:
        upscale: 0
        downscale: 0
