speeds:
        WAY: 4
        PARK: 3
        GREEN: 3
        FOREST: 2
        PAVED: 4
        UNPAVED: 3
        STEPS: 2
        HIGHWAY: 4
        DIRECT: 3
        GENERATED: 3

ratios:
        PARK: 1
        GREEN: 1
        FOREST: 0.75
        PAVED: 1.2
        UNPAVED: 1
        STEPS: 0.6
        HIGHWAY: 1.2
        DIRECT: 0.8
        GENERATED: 1
penalties:
        HIGHWAY: 1
        DIRECT: 1
heights:
        upscale: 0
        downscale: 0
pt-time-penalties:
        tram: 1
        metro: 1
        rail: 1
        bus: 1
        ferry: 1
        cable-car: 1
        gondola: 1
        funicular: 1
pt-fixed-penalties:
        tram: 0
        metro: 0
        rail: 0
        bus: 0
        ferry: 0
        cable-car: 0
        gondola: 0
        funicular: 0
line-penalties: 
        201: 0
max-vehicles: 10
geton-penalty: 0
min-wait: 30
