yes:
        0:
            tunnel: "*"
            indoor:
                - "yes"
            layer:
                - "-1"
                - "-2"
                - "-3"
                - "-4"
                - "-5"

            station:
                - "subway"
            transport:
                - "subway"

no:
        0:
            tunnel:
                - "no"
