Way:
    ignore: 
        boundary : "*"
        natural:
            - tree_row
        railway:
            - subway
    barrier: 
        barrier : "*"
        waterway:
            - river
            - canal
            - weir
        building: "*"
        landuse:
            - allotments
            - basin
            - construction
            - cemetery
            - garages
            - greenhoue_horticulture
            - landfill
            - military 
            - reservoir
            - vineyard
 
        leisure:
            - garden
            - pitch
            - stadium
        highway:
            - motorway
            - trunk
            - motorway-link
            - trunk-link
    
    railway:
        railway:
            - funicular
            - light_rail
            - rail
        landuse:
            - railway
    water:
        waterway:
            - riverbank
            - stream
    park:
        leisure:
            - park
            - playground
        landuse:
            - grass
            - recreation_ground
            - village_green
        natural:
            - grassland

    green:
        leisure:
            - common
            - nature_reserve
        landuse:
            - farm
            - farmland
            - meadow
            - orchad
            - pasture
        natural:
            - scrub
            - heath
            - sand

    forest:
        landuse:
            - forest
    paved:
        landuse:
            - residential
            - industrial
        amenity:
            - parking
            - fuel
        highway:
            - residential
            - service
            - living_street
            - pedestrian
            - track
            - footway
            - cycleway
        area:highway:
            - pedestrian
        cycleway:
            - track
    steps:
        highway:
            - steps
    unpaved:
        highway:
            - track
            - path
            - bridleway
    highway:
        highway:
            - primary
            - secondary
            - tertiary

        



