IGNORE: 
    boundary : "*"
    natural:
        - tree_row
    railway:
        - subway
    landuse:
        -residential
BARRIER: 
    barrier : "*"
    waterway:
        - river
        - canal
        - weir
    building: "*"
    landuse:
        - allotments
        - basin
        - construction
        - cemetery
        - garages
        - greenhoue_horticulture
        - landfill
        - military 
        - reservoir
        - vineyard

    leisure:
        - garden
        - pitch
        - stadium
    highway:
        - motorway
        - trunk
        - motorway-link
        - trunk-link
        - primary
        - primary-link
    railway:
        - funicular
        - light_rail
        - rail

RAILWAY:
    landuse:
        - railway
WATER:
    waterway:
        - riverbank
        - stream
PARK:
    leisure:
        - park
        - playground
    landuse:
        - grass
        - recreation_ground
        - village_green
    natural:
        - grassland

GREEN:
    leisure:
        - common
        - nature_reserve
    landuse:
        - farm
        - farmland
        - meadow
        - orchad
        - pasture
    natural:
        - scrub
        - heath
        - sand

FOREST:
    landuse:
        - forest
PAVED:
    landuse:
        - residential
        - industrial
    amenity:
        - parking
        - fuel
    highway:
        - residential
        - service
        - living_street
        - pedestrian
        - track
        - footway
        - cycleway
    area:highway:
        - pedestrian
    cycleway:
        - track
STEPS:
    highway:
        - steps
UNPAVED:
    highway:
        - track
        - path
        - bridleway
HIGHWAY:
    highway:
        - secondary
        - tertiary

        



