IGNORE: 
        0:
            boundary : "*"
            natural:
                - tree_row
            railway:
                - subway
            landuse:
                - residential
                - industrial
        1:
            access:
                - no
                - private
            foot:
                - no
            barrier:
                - kerb
                - bollard
        2:
            route:
                - ferry
BARRIER: 
        0:
            barrier : "*"
            waterway:
                - river
                - riverbank
                - canal
                - weir
                - stream
            building: "*"
            "building:part": yes
            landuse:
                - allotments
                - basin
                - construction
                - cemetery
                - garages
                - greenhoue_horticulture
                - landfill
                - military 
                - reservoir
                - vineyard
                - railway

            leisure:
                - garden
                - pitch
                - stadium
            highway:
                - motorway
                - trunk
                - motorway_link
                - trunk_link
                - primary
                - primary_link
            railway:
                - funicular
                - light_rail
                - rail
            natural:
                - cliff
                - scrub

#RAILWAY:
#WATER:
#        0:
#            waterway:
#                - riverbank
#                - stream
#PARK:
#        0:
#            leisure:
#                - park
#                - playground
#            landuse:
#                - grass
#                - recreation_ground
#                - village_green
#            natural:
#                - grassland
#
#GREEN:
#        0:
#            leisure:
#                - common
#                - nature_reserve
#            landuse:
#                - farm
#                - farmland
#                - meadow
#                - orchad
#                - pasture
#            natural:
#                - scrub
#                - heath
#                - sand
#
#FOREST:
#        0:
#            landuse:
#                - forest
PAVED:
        0:
            amenity:
                - parking
                - fuel
            highway:
                - residential
                - service
                - living_street
                - pedestrian
                - track
                - footway
                - cycleway
                - unclassified
            area:highway:
                - pedestrian
            cycleway:
                - track
            public_transport:
                - platform
        1:
            foot:
                - yes
STEPS:
        0:
            highway:
                - steps
UNPAVED:
        0:
            highway:
                - track
                - path
                - bridleway
HIGHWAY:
        0:
            highway:
                - secondary
                - tertiary
